[package]
name = "grouch-scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.61"
tokio = { version = "1", features = ["full"] }
rocket = "0.5.0-rc.2"
